In [3]:
import pandas as pd

In [4]:
df = pd.read_csv(r"C:\Users\USER\OneDrive\Desktop\Webfala\pandas\titanic.csv")
df.head()

,Survived,Pclass,Name,Sex,Age,SibSp,PaCh,Fare
0,0,3,Mr. Owen Harris Braund,male,22.0,1,0,7.2500
1,1,1,Mrs. John Bradley (Florence Briggs Thayer) Cum...,female,38.0,1,0,71.2833
2,1,3,Miss. Laina Heikkinen,female,26.0,0,0,7.9250
3,1,1,Mrs. Jacques Heath (Lily May Peel) Futrelle,female,35.0,1,0,53.1000
4,0,3,Mr. William Henry Allen,male,35.0,0,0,8.0500

In [4]:
# Inspecting the structure
#(rows, columns)
df.shape

(887, 8)

In [5]:
# Column names
df.columns

Index(['Survived', 'Pclass', 'Name', 'Sex', 'Age', 'SibSp', 'PaCh', 'Fare'], dtype='object')

In [6]:
# Row index
df.index

RangeIndex(start=0, stop=887, step=1)

In [7]:
# data types of each colum
df.dtypes

Survived      int64
Pclass        int64
Name         object
Sex          object
Age         float64
SibSp         int64
PaCh          int64
Fare        float64
dtype: object

In [11]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 887 entries, 0 to 886
Data columns (total 8 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Survived  887 non-null    int64
 1   Pclass    887 non-null    int64
 2   Name      887 non-null    object
 3   Sex       887 non-null    object
 4   Age       887 non-null    float64
 5   SibSp     887 non-null    int64
 6   PaCh      887 non-null    int64
 7   Fare      887 non-null    float64
dtypes: float64(2), int64(4), object(2)
memory usage: 55.6+ KB

In [13]:
df["Age"].sum()

np.float64(26141.17)

In [16]:
df["Age"].mean()

np.float64(29.471443066516347)

In [17]:
df.tail()

,Survived,Pclass,Name,Sex,Age,SibSp,PaCh,Fare
882,0,2,Rev. Juozas Montvila,male,27.0,0,0,13.00
883,1,1,Miss. Margaret Edith Graham,female,19.0,0,0,30.00
884,0,3,Miss. Catherine Helen Johnston,female,7.0,1,2,23.45
885,1,1,Mr. Karl Howell Behr,male,26.0,0,0,30.00
886,0,3,Mr. Patrick Dooley,male,32.0,0,0,7.75

In [18]:
# Random 5 rows
df.sample(5)

,Survived,Pclass,Name,Sex,Age,SibSp,PaCh,Fare
639,0,3,Miss. Margit Elizabeth Skoog,female,2.0,3,2,27.900
349,0,1,Mr. Fletcher Fellows Williams-Lambert,male,43.0,0,0,35.000
265,1,3,Mr. Ernst Ulrik Persson,male,25.0,1,0,7.775
526,0,2,Mr. Richard George Hocking,male,23.0,2,1,11.500
586,0,3,Mr. Joseph Murdlin,male,22.0,0,0,8.050

In [19]:
# To make a copy when you want to make changes to the data
new_df = df.copy()
new_df

,Survived,Pclass,Name,Sex,Age,SibSp,PaCh,Fare
0,0,3,Mr. Owen Harris Braund,male,22.0,1,0,7.2500
1,1,1,Mrs. John Bradley (Florence Briggs Thayer) Cum...,female,38.0,1,0,71.2833
2,1,3,Miss. Laina Heikkinen,female,26.0,0,0,7.9250
3,1,1,Mrs. Jacques Heath (Lily May Peel) Futrelle,female,35.0,1,0,53.1000
4,0,3,Mr. William Henry Allen,male,35.0,0,0,8.0500
...,...,...,...,...,...,...,...,...
882,0,2,Rev. Juozas Montvila,male,27.0,0,0,13.0000
883,1,1,Miss. Margaret Edith Graham,female,19.0,0,0,30.0000
884,0,3,Miss. Catherine Helen Johnston,female,7.0,1,2,23.4500
885,1,1,Mr. Karl Howell Behr,male,26.0,0,0,30.0000
886,0,3,Mr. Patrick Dooley,male,32.0,0,0,7.7500

In [20]:
# shows the frequency of unique values in a column (used mostly for categorical )
df['Sex'].value_counts()

Sex
male      573
female    314
Name: count, dtype: int64

In [21]:
df['Pclass'].value_counts()

Pclass
3    487
1    216
2    184
Name: count, dtype: int64

In [24]:
# Provides descriptive statistics for numeric columns(mean, std, min, max)
#df.describe(include = 'all')  #for all data types
df.describe()

         Survived      Pclass         Age       SibSp        PaCh       Fare
count  887.000000  887.000000  887.000000  887.000000  887.000000  887.00000
mean     0.385569    2.305524   29.471443    0.525366    0.383315   32.30542
std      0.487004    0.836662   14.121908    1.104669    0.807466   49.78204
min      0.000000    1.000000    0.420000    0.000000    0.000000    0.00000
25%      0.000000    2.000000   20.250000    0.000000    0.000000    7.92500
50%      0.000000    3.000000   28.000000    0.000000    0.000000   14.45420
75%      1.000000    3.000000   38.000000    1.000000    0.000000   31.13750
max      1.000000    3.000000   80.000000    8.000000    6.000000  512.32920

In [25]:
# Selecting columns

# Single column as series
df['Name'] # for series
df[['Name']]  #for data frame

                                                  Name
0                               Mr. Owen Harris Braund
1    Mrs. John Bradley (Florence Briggs Thayer) Cum...
2                                Miss. Laina Heikkinen
3          Mrs. Jacques Heath (Lily May Peel) Futrelle
4                              Mr. William Henry Allen
..                                                 ...
882                               Rev. Juozas Montvila
883                        Miss. Margaret Edith Graham
884                     Miss. Catherine Helen Johnston
885                               Mr. Karl Howell Behr
886                                 Mr. Patrick Dooley

[887 rows x 1 columns]

In [26]:
df.iloc[:, 2]

0                                 Mr. Owen Harris Braund
1      Mrs. John Bradley (Florence Briggs Thayer) Cum...
2                                  Miss. Laina Heikkinen
3            Mrs. Jacques Heath (Lily May Peel) Futrelle
4                                Mr. William Henry Allen
                             ...
882                                 Rev. Juozas Montvila
883                          Miss. Margaret Edith Graham
884                       Miss. Catherine Helen Johnston
885                                 Mr. Karl Howell Behr
886                                   Mr. Patrick Dooley
Name: Name, Length: 887, dtype: object

In [28]:
df.iloc[:, 4]

0      22.0
1      38.0
2      26.0
3      35.0
4      35.0
       ...
882    27.0
883    19.0
884     7.0
885    26.0
886    32.0
Name: Age, Length: 887, dtype: float64

In [32]:
df.iloc[0:3, 2]

0                               Mr. Owen Harris Braund
1    Mrs. John Bradley (Florence Briggs Thayer) Cum...
2                                Miss. Laina Heikkinen
Name: Name, dtype: object

In [39]:
# single column as a dataframe using index location, pass in the column index number as a list
df.iloc[:, [2]]

                                                  Name
0                               Mr. Owen Harris Braund
1    Mrs. John Bradley (Florence Briggs Thayer) Cum...
2                                Miss. Laina Heikkinen
3          Mrs. Jacques Heath (Lily May Peel) Futrelle
4                              Mr. William Henry Allen
..                                                 ...
882                               Rev. Juozas Montvila
883                        Miss. Margaret Edith Graham
884                     Miss. Catherine Helen Johnston
885                               Mr. Karl Howell Behr
886                                 Mr. Patrick Dooley

[887 rows x 1 columns]

In [43]:
# Multiple columns as Dataframe and return the first five
df[['Name', 'Age']][:5]

                                                Name   Age
0                             Mr. Owen Harris Braund  22.0
1  Mrs. John Bradley (Florence Briggs Thayer) Cum...  38.0
2                              Miss. Laina Heikkinen  26.0
3        Mrs. Jacques Heath (Lily May Peel) Futrelle  35.0
4                            Mr. William Henry Allen  35.0

In [46]:
# selecting rows by index
# first row (by position)

df.iloc[0]
# To always get it in a dataframe put the index number in a list
df.iloc[[0]]

   Survived  Pclass                    Name   Sex   Age  SibSp  PaCh  Fare
0         0       3  Mr. Owen Harris Braund  male  22.0      1     0  7.25

In [45]:
df[:3]

,Survived,Pclass,Name,Sex,Age,SibSp,PaCh,Fare
0,0,3,Mr. Owen Harris Braund,male,22.0,1,0,7.2500
1,1,1,Mrs. John Bradley (Florence Briggs Thayer) Cum...,female,38.0,1,0,71.2833
2,1,3,Miss. Laina Heikkinen,female,26.0,0,0,7.9250

In [47]:
df[50:55]

,Survived,Pclass,Name,Sex,Age,SibSp,PaCh,Fare
50,0,3,Mr. Richard Cater Nosworthy,male,21.0,0,0,7.8000
51,1,1,Mrs. Henry Sleeper (Myna Haxtun) Harper,female,49.0,1,0,76.7292
52,1,2,Mrs. Lizzie (Elizabeth Anne Wilkinson) Faunthorpe,female,29.0,1,0,26.0000
53,0,1,Mr. Engelhart Cornelius Ostby,male,65.0,0,1,61.9792
54,1,1,Mr. Hugh Woolner,male,46.0,0,0,35.5000

In [ ]:
# Row with label/index
df.loc[0]

In [49]:
# selecting by condition

df[df['Age'] > 60].head(5)

,Survived,Pclass,Name,Sex,Age,SibSp,PaCh,Fare
33,0,2,Mr. Edward H Wheadon,male,66.0,0,0,10.5000
53,0,1,Mr. Engelhart Cornelius Ostby,male,65.0,0,1,61.9792
63,0,1,Mr. Albert A Stewart,male,64.0,0,0,27.7208
95,0,1,Mr. George B Goldschmidt,male,71.0,0,0,34.6542
115,0,3,Mr. Patrick Connors,male,70.5,0,0,7.7500

In [50]:
# Mixed selection
#Format: df.loc[row_indexer, column_indexer]

df.loc[0,'Name']

'Mr. Owen Harris Braund'

In [51]:
df.iloc[0,2] # remember; cols are also indexed

'Mr. Owen Harris Braund'

In [52]:
df.iloc[1,2]

'Mrs. John Bradley (Florence Briggs Thayer) Cumings'

In [53]:
#Rows from index 0 to 2 (the last index number inclusive for loc)
df.loc[0:2]

,Survived,Pclass,Name,Sex,Age,SibSp,PaCh,Fare
0,0,3,Mr. Owen Harris Braund,male,22.0,1,0,7.2500
1,1,1,Mrs. John Bradley (Florence Briggs Thayer) Cum...,female,38.0,1,0,71.2833
2,1,3,Miss. Laina Heikkinen,female,26.0,0,0,7.9250

In [54]:
# All rows, selected columns
df.loc[:, ['Name','Age']]

                                                  Name   Age
0                               Mr. Owen Harris Braund  22.0
1    Mrs. John Bradley (Florence Briggs Thayer) Cum...  38.0
2                                Miss. Laina Heikkinen  26.0
3          Mrs. Jacques Heath (Lily May Peel) Futrelle  35.0
4                              Mr. William Henry Allen  35.0
..                                                 ...   ...
882                               Rev. Juozas Montvila  27.0
883                        Miss. Margaret Edith Graham  19.0
884                     Miss. Catherine Helen Johnston   7.0
885                               Mr. Karl Howell Behr  26.0
886                                 Mr. Patrick Dooley  32.0

[887 rows x 2 columns]

## Selecting by condition

In [4]:
df[df['Age'] > 60]

,Survived,Pclass,Name,Sex,Age,SibSp,PaCh,Fare
33,0,2,Mr. Edward H Wheadon,male,66.0,0,0,10.5000
53,0,1,Mr. Engelhart Cornelius Ostby,male,65.0,0,1,61.9792
63,0,1,Mr. Albert A Stewart,male,64.0,0,0,27.7208
95,0,1,Mr. George B Goldschmidt,male,71.0,0,0,34.6542
115,0,3,Mr. Patrick Connors,male,70.5,0,0,7.7500
169,0,1,Mr. Wyckoff Van der hoef,male,61.0,0,0,33.5000
251,0,1,Mr. William Thomas Stead,male,62.0,0,0,26.5500
273,1,1,Miss. Kornelia Theodosia Andrews,female,63.0,1,0,77.9583
278,0,3,Mr. Frank Duane,male,65.0,0,0,7.7500
324,0,3,Mr. Johan Hansen Nysveen,male,61.0,0,0,6.2375
435,0,1,Mr. Mark Fortune,male,64.0,1,4,263.0000
453,0,1,Mr. Francis Davis Millet,male,65.0,0,0,26.5500
480,1,3,Mrs. (Hedwig) Turkula,female,63.0,0,0,9.5875
490,0,1,Mr. Ramon Artagaveytia,male,71.0,0,0,49.5042
508,0,3,Mr. James Webber,male,66.0,0,0,8.0500
535,0,3,Mr. Samuel Beard Risien,male,69.0,0,0,14.5000
542,0,1,Mr. Arthur Ernest Nicholson,male,64.0,0,0,26.0000
552,0,1,Mr. George Wright,male,62.0,0,0,26.5500
561,0,3,Miss. (Marion Ogden) Meanwell,female,62.0,0,0,8.0500
567,1,2,Mr. George Harris,male,62.0,0,0,10.5000
622,0,1,Mr. Frederick Sutton,male,61.0,0,0,32.3208
627,1,1,Mr. Algernon Henry Wilson Barkworth,male,80.0,0,0,30.0000
669,0,2,Mr. Henry Michael Mitchell,male,70.0,0,0,10.5000
741,0,1,Capt. Edward Gifford Crosby,male,70.0,1,1,71.0000
825,1,1,Mrs. George Nelson (Martha Evelyn) Stone,female,62.0,0,0,80.0000
847,0,3,Mr. Johan Svensson,male,74.0,0,0,7.7750

In [6]:
# mixed selection
# Format: df.loc[row_indexer, column_indexer]

df.loc[0, 'Name']

'Mr. Owen Harris Braund'

In [7]:
df.iloc[0, 2] # remembber: cols are also indexed

'Mr. Owen Harris Braund'

In [8]:
df.iloc[1, 2]

'Mrs. John Bradley (Florence Briggs Thayer) Cumings'

In [9]:
# Rows from index 0 to 2 (inclusive)
df.loc[0:2]

,Survived,Pclass,Name,Sex,Age,SibSp,PaCh,Fare
0,0,3,Mr. Owen Harris Braund,male,22.0,1,0,7.2500
1,1,1,Mrs. John Bradley (Florence Briggs Thayer) Cum...,female,38.0,1,0,71.2833
2,1,3,Miss. Laina Heikkinen,female,26.0,0,0,7.9250

In [10]:
# All rows, selected columns
df.loc[:, ['Name', 'Age']]

                                                  Name   Age
0                               Mr. Owen Harris Braund  22.0
1    Mrs. John Bradley (Florence Briggs Thayer) Cum...  38.0
2                                Miss. Laina Heikkinen  26.0
3          Mrs. Jacques Heath (Lily May Peel) Futrelle  35.0
4                              Mr. William Henry Allen  35.0
..                                                 ...   ...
882                               Rev. Juozas Montvila  27.0
883                        Miss. Margaret Edith Graham  19.0
884                     Miss. Catherine Helen Johnston   7.0
885                               Mr. Karl Howell Behr  26.0
886                                 Mr. Patrick Dooley  32.0

[887 rows x 2 columns]

In [11]:
# Names where Age > 30
df.loc[df['Age'] > 30, ['Name']

1      Mrs. John Bradley (Florence Briggs Thayer) Cum...
3            Mrs. Jacques Heath (Lily May Peel) Futrelle
4                                Mr. William Henry Allen
6                                 Mr. Timothy J McCarthy
11                               Miss. Elizabeth Bonnell
                             ...
869                           Mr. Victor Vander Cruyssen
875         Mrs. Thomas Jr (Lily Alexenia Wilson) Potter
877                                    Mr. Johann Markun
881                  Mrs. William (Margaret Norton) Rice
886                                   Mr. Patrick Dooley
Name: Name, Length: 362, dtype: object

In [25]:
# Quick task, return name and age of those >= 70
df[df['Age'] > 70, ['Name','Age']]

InvalidIndexError: (0      False
1      False
2      False
3      False
4      False
       ...
882    False
883    False
884    False
885    False
886    False
Name: Age, Length: 887, dtype: bool, ['Name', 'Age'])

In [23]:
df.loc[df['Age'] > 70, ['Name', 'Age']]

                                    Name   Age
95              Mr. George B Goldschmidt  71.0
115                  Mr. Patrick Connors  70.5
490               Mr. Ramon Artagaveytia  71.0
627  Mr. Algernon Henry Wilson Barkworth  80.0
847                   Mr. Johan Svensson  74.0

In [26]:
# .iloc[] – Integer-location based selection: Select rows and columns by
# Format: df.iloc[row_idx, col_idx]
# First row
df.iloc[0, 2]

'Mr. Owen Harris Braund'

In [27]:
# All rows, columns 0 and 2
df.iloc[:, [0, 2]]

     Survived                                               Name
0           0                             Mr. Owen Harris Braund
1           1  Mrs. John Bradley (Florence Briggs Thayer) Cum...
2           1                              Miss. Laina Heikkinen
3           1        Mrs. Jacques Heath (Lily May Peel) Futrelle
4           0                            Mr. William Henry Allen
..        ...                                                ...
882         0                               Rev. Juozas Montvila
883         1                        Miss. Margaret Edith Graham
884         0                     Miss. Catherine Helen Johnston
885         1                               Mr. Karl Howell Behr
886         0                                 Mr. Patrick Dooley

[887 rows x 2 columns]

## Basic Operations

In [28]:
df[df['Fare'] > 250]

,Survived,Pclass,Name,Sex,Age,SibSp,PaCh,Fare
27,0,1,Mr. Charles Alexander Fortune,male,19.0,3,2,263.0000
87,1,1,Miss. Mabel Helen Fortune,female,23.0,3,2,263.0000
257,1,1,Miss. Anna Ward,female,35.0,0,0,512.3292
309,1,1,Miss. Emily Borie Ryerson,female,18.0,2,2,262.3750
339,1,1,Miss. Alice Elizabeth Fortune,female,24.0,3,2,263.0000
435,0,1,Mr. Mark Fortune,male,64.0,1,4,263.0000
676,1,1,Mr. Thomas Drake Martinez Cardeza,male,36.0,0,1,512.3292
733,1,1,Mr. Gustave J Lesurer,male,35.0,0,0,512.3292
738,1,1,Miss. Susan Parker Ryerson,female,21.0,2,2,262.3750

In [29]:
df[(df['Age'] > 25) & (df['Fare'] > 250)]

,Survived,Pclass,Name,Sex,Age,SibSp,PaCh,Fare
257,1,1,Miss. Anna Ward,female,35.0,0,0,512.3292
435,0,1,Mr. Mark Fortune,male,64.0,1,4,263.0000
676,1,1,Mr. Thomas Drake Martinez Cardeza,male,36.0,0,1,512.3292
733,1,1,Mr. Gustave J Lesurer,male,35.0,0,0,512.3292

In [30]:
# String condition
df[df['Name'].str.contains('Rose')]

,Survived,Pclass,Name,Sex,Age,SibSp,PaCh,Fare
851,1,3,Mrs. Sam (Leah Rosen) Aks,female,18.0,0,1,9.35

In [31]:
# class task
# select all where sex=female and survived=0
df[(df['Sex'] == 'female') & (df['Survived'] == 0)]

,Survived,Pclass,Name,Sex,Age,SibSp,PaCh,Fare
14,0,3,Miss. Hulda Amanda Adolfina Vestrom,female,14.0,0,0,7.8542
18,0,3,Mrs. Julius (Emelia Maria Vandemoortele) Vande...,female,31.0,1,0,18.0000
24,0,3,Miss. Torborg Danira Palsson,female,8.0,3,1,21.0750
38,0,3,Miss. Augusta Maria Vander Planke,female,18.0,2,0,18.0000
40,0,3,Mrs. Johan (Johanna Persdotter Larsson) Ahlin,female,40.0,1,0,9.4750
...,...,...,...,...,...,...,...,...
850,0,2,Mrs. Ernest Courtenay (Lilian Hughes) Carter,female,44.0,1,0,26.0000
859,0,3,Miss. Dorothy Edith Sage,female,14.0,8,2,69.5500
878,0,3,Miss. Gerda Ulrika Dahlberg,female,22.0,0,0,10.5167
881,0,3,Mrs. William (Margaret Norton) Rice,female,39.0,0,5,29.1250
884,0,3,Miss. Catherine Helen Johnston,female,7.0,1,2,23.4500

## Setting and Resetting Indexes

In [37]:
# Set a column as index
# Use a list to pass as the new index and the elements in the list must be equal to the number of rows
df.set_index('Name', inplace=True)

In [38]:
df.head()

,Survived,Pclass,Sex,Age,SibSp,PaCh,Fare
Name,,,,,,,
Mr. Owen Harris Braund,0,3,male,22.0,1,0,7.2500
Mrs. John Bradley (Florence Briggs Thayer) Cumings,1,1,female,38.0,1,0,71.2833
Miss. Laina Heikkinen,1,3,female,26.0,0,0,7.9250
Mrs. Jacques Heath (Lily May Peel) Futrelle,1,1,female,35.0,1,0,53.1000
Mr. William Henry Allen,0,3,male,35.0,0,0,8.0500

In [39]:
# Reset index back to default
df.reset_index(inplace=True)

In [40]:
df.head()

,Name,Survived,Pclass,Sex,Age,SibSp,PaCh,Fare
0,Mr. Owen Harris Braund,0,3,male,22.0,1,0,7.2500
1,Mrs. John Bradley (Florence Briggs Thayer) Cum...,1,1,female,38.0,1,0,71.2833
2,Miss. Laina Heikkinen,1,3,female,26.0,0,0,7.9250
3,Mrs. Jacques Heath (Lily May Peel) Futrelle,1,1,female,35.0,1,0,53.1000
4,Mr. William Henry Allen,0,3,male,35.0,0,0,8.0500

In [34]:
# Querying DataFrames with df.query(): More readable way to filter rows u
# Age > 30
df.query('Age > 30')

,Survived,Pclass,Sex,Age,SibSp,PaCh,Fare
Name,,,,,,,
Mrs. John Bradley (Florence Briggs Thayer) Cumings,1,1,female,38.0,1,0,71.2833
Mrs. Jacques Heath (Lily May Peel) Futrelle,1,1,female,35.0,1,0,53.1000
Mr. William Henry Allen,0,3,male,35.0,0,0,8.0500
Mr. Timothy J McCarthy,0,1,male,54.0,0,0,51.8625
Miss. Elizabeth Bonnell,1,1,female,58.0,0,0,26.5500
...,...,...,...,...,...,...,...
Mr. Victor Vander Cruyssen,0,3,male,47.0,0,0,9.0000
Mrs. Thomas Jr (Lily Alexenia Wilson) Potter,1,1,female,56.0,0,1,83.1583
Mr. Johann Markun,0,3,male,33.0,0,0,7.8958
Mrs. William (Margaret Norton) Rice,0,3,female,39.0,0,5,29.1250
Mr. Patrick Dooley,0,3,male,32.0,0,0,7.7500

In [42]:
# Multiple or combined conditions with query
df.query("Age > 70 and Sex == 'male'")

,Name,Survived,Pclass,Sex,Age,SibSp,PaCh,Fare
95,Mr. George B Goldschmidt,0,1,male,71.0,0,0,34.6542
115,Mr. Patrick Connors,0,3,male,70.5,0,0,7.7500
490,Mr. Ramon Artagaveytia,0,1,male,71.0,0,0,49.5042
627,Mr. Algernon Henry Wilson Barkworth,1,1,male,80.0,0,0,30.0000
847,Mr. Johan Svensson,0,3,male,74.0,0,0,7.7750

In [45]:
# Stirng match
df.query('Name == "Mr. Johan Svensson"')

                   Name  Survived  Pclass   Sex   Age  SibSp  PaCh   Fare
847  Mr. Johan Svensson         0       3  male  74.0      0     0  7.775

In [46]:
# Sort by a column
df.sort_values(by='Age')

,Name,Survived,Pclass,Sex,Age,SibSp,PaCh,Fare
799,Master. Assad Alexander Thomas,1,3,male,0.42,0,1,8.5167
751,Master. Viljo Hamalainen,1,2,male,0.67,1,1,14.5000
641,Miss. Eugenie Baclini,1,3,female,0.75,2,1,19.2583
466,Miss. Helene Barbara Baclini,1,3,female,0.75,2,1,19.2583
827,Master. George Sibley Richards,1,2,male,0.83,1,1,18.7500
...,...,...,...,...,...,...,...,...
115,Mr. Patrick Connors,0,3,male,70.50,0,0,7.7500
490,Mr. Ramon Artagaveytia,0,1,male,71.00,0,0,49.5042
95,Mr. George B Goldschmidt,0,1,male,71.00,0,0,34.6542
847,Mr. Johan Svensson,0,3,male,74.00,0,0,7.7750
627,Mr. Algernon Henry Wilson Barkworth,1,1,male,80.00,0,0,30.0000

In [47]:
# Descending order
df.sort_values(by='Age', ascending=False)

,Name,Survived,Pclass,Sex,Age,SibSp,PaCh,Fare
627,Mr. Algernon Henry Wilson Barkworth,1,1,male,80.00,0,0,30.0000
847,Mr. Johan Svensson,0,3,male,74.00,0,0,7.7750
490,Mr. Ramon Artagaveytia,0,1,male,71.00,0,0,49.5042
95,Mr. George B Goldschmidt,0,1,male,71.00,0,0,34.6542
115,Mr. Patrick Connors,0,3,male,70.50,0,0,7.7500
...,...,...,...,...,...,...,...,...
77,Master. Alden Gates Caldwell,1,2,male,0.83,0,2,29.0000
466,Miss. Helene Barbara Baclini,1,3,female,0.75,2,1,19.2583
641,Miss. Eugenie Baclini,1,3,female,0.75,2,1,19.2583
751,Master. Viljo Hamalainen,1,2,male,0.67,1,1,14.5000
799,Master. Assad Alexander Thomas,1,3,male,0.42,0,1,8.5167

In [48]:
#Return just only the names
df.sort_values(by='Age', ascending=False)["Name"]

627    Mr. Algernon Henry Wilson Barkworth
847                     Mr. Johan Svensson
490                 Mr. Ramon Artagaveytia
95                Mr. George B Goldschmidt
115                    Mr. Patrick Connors
                      ...
77            Master. Alden Gates Caldwell
466           Miss. Helene Barbara Baclini
641                  Miss. Eugenie Baclini
751               Master. Viljo Hamalainen
799         Master. Assad Alexander Thomas
Name: Name, Length: 887, dtype: object

In [49]:
# You can sort by muktiple columns
df.sort_values(['Age', 'Fare'])
# Note: This sorts by the Age column first. If multiple rows have the exact same age
# the code uses the Fare column to break the tie (also in ascending order, from lowest to highest

,Name,Survived,Pclass,Sex,Age,SibSp,PaCh,Fare
799,Master. Assad Alexander Thomas,1,3,male,0.42,0,1,8.5167
751,Master. Viljo Hamalainen,1,2,male,0.67,1,1,14.5000
466,Miss. Helene Barbara Baclini,1,3,female,0.75,2,1,19.2583
641,Miss. Eugenie Baclini,1,3,female,0.75,2,1,19.2583
827,Master. George Sibley Richards,1,2,male,0.83,1,1,18.7500
...,...,...,...,...,...,...,...,...
115,Mr. Patrick Connors,0,3,male,70.50,0,0,7.7500
95,Mr. George B Goldschmidt,0,1,male,71.00,0,0,34.6542
490,Mr. Ramon Artagaveytia,0,1,male,71.00,0,0,49.5042
847,Mr. Johan Svensson,0,3,male,74.00,0,0,7.7750
627,Mr. Algernon Henry Wilson Barkworth,1,1,male,80.00,0,0,30.0000

In [51]:
# Sort by index (the default)
df.sort_index(ascending = False)

# # This will sort different if you used a different index like we did above

,Name,Survived,Pclass,Sex,Age,SibSp,PaCh,Fare
886,Mr. Patrick Dooley,0,3,male,32.0,0,0,7.7500
885,Mr. Karl Howell Behr,1,1,male,26.0,0,0,30.0000
884,Miss. Catherine Helen Johnston,0,3,female,7.0,1,2,23.4500
883,Miss. Margaret Edith Graham,1,1,female,19.0,0,0,30.0000
882,Rev. Juozas Montvila,0,2,male,27.0,0,0,13.0000
...,...,...,...,...,...,...,...,...
4,Mr. William Henry Allen,0,3,male,35.0,0,0,8.0500
3,Mrs. Jacques Heath (Lily May Peel) Futrelle,1,1,female,35.0,1,0,53.1000
2,Miss. Laina Heikkinen,1,3,female,26.0,0,0,7.9250
1,Mrs. John Bradley (Florence Briggs Thayer) Cum...,1,1,female,38.0,1,0,71.2833
0,Mr. Owen Harris Braund,0,3,male,22.0,1,0,7.2500

## Grouping (groupby)

In [55]:
# Group by class
class_group = df.groupby('Pclass')
# This alone is not useful, unless you use operation (like .sum() or .mean()

In [53]:
# Aggregate functions

# Mean fare per class
class_group['Fare'].mean()

Pclass
1    84.154687
2    20.662183
3    13.707707
Name: Fare, dtype: float64

In [56]:
# Total Fare per class
class_group['Fare'].sum()

Pclass
1    18177.4125
2     3801.8417
3     6675.6535
Name: Fare, dtype: float64

In [57]:
# Multiple aggregations

class_group.agg({'Fare': ['mean', 'max','min']})

             Fare
             mean       max  min
Pclass
1       84.154687  512.3292  0.0
2       20.662183   73.5000  0.0
3       13.707707   69.5500  0.0

In [59]:
# class task
# find the passengers with the max and min fare from each class
df[df['Fare'] == 512.3292]

,Name,Survived,Pclass,Sex,Age,SibSp,PaCh,Fare
257,Miss. Anna Ward,1,1,female,35.0,0,0,512.3292
676,Mr. Thomas Drake Martinez Cardeza,1,1,male,36.0,0,1,512.3292
733,Mr. Gustave J Lesurer,1,1,male,35.0,0,0,512.3292

In [60]:
df[df['Fare'] == 73.5000]

,Name,Survived,Pclass,Sex,Age,SibSp,PaCh,Fare
71,Mr. Ambrose Jr Hood,0,2,male,21.0,0,0,73.5
119,Mr. Stanley George Hickman,0,2,male,21.0,2,0,73.5
383,Mr. Charles Henry Davies,0,2,male,18.0,0,0,73.5
652,Mr. Leonard Mark Hickman,0,2,male,24.0,2,0,73.5
662,Mr. Lewis Hickman,0,2,male,32.0,2,0,73.5

In [61]:
df[df['Fare'] == 69.5500]

,Name,Survived,Pclass,Sex,Age,SibSp,PaCh,Fare
158,Master. Thomas Henry Sage,0,3,male,5.0,8,2,69.55
179,Miss. Constance Gladys Sage,0,3,female,8.0,8,2,69.55
200,Mr. Frederick Sage,0,3,male,17.0,8,2,69.55
322,Mr. George John Jr Sage,0,3,male,20.0,8,2,69.55
788,Miss. Stella Anna Sage,0,3,female,21.0,8,2,69.55
842,Mr. Douglas Bullen Sage,0,3,male,18.0,8,2,69.55
859,Miss. Dorothy Edith Sage,0,3,female,14.0,8,2,69.55

In [63]:
# Simple condition
df[df['Fare'] == 0.0]

,Name,Survived,Pclass,Sex,Age,SibSp,PaCh,Fare
178,Mr. Lionel Leonard,0,3,male,36.0,0,0,0.0
261,Mr. William Harrison,0,1,male,40.0,0,0,0.0
269,Mr. William Henry Tornquist,1,3,male,25.0,0,0,0.0
275,Mr. Francis Parkes,0,2,male,21.0,0,0,0.0
300,Mr. William Cahoone Jr Johnson,0,3,male,19.0,0,0,0.0
411,Mr. Alfred Fleming Cunningham,0,2,male,22.0,0,0,0.0
463,Mr. William Campbell,0,2,male,21.0,0,0,0.0
478,Mr. Anthony Wood Frost,0,2,male,37.0,0,0,0.0
594,Mr. Alfred Johnson,0,3,male,49.0,0,0,0.0
630,Mr. William Henry Marsh Parr,0,1,male,30.0,0,0,0.0
671,Mr. Ennis Hastings Watson,0,2,male,19.0,0,0,0.0
728,Mr. Robert J Knight,0,2,male,41.0,0,0,0.0
802,Mr. Thomas Jr Andrews,0,1,male,39.0,0,0,0.0
811,Mr. Richard Fry,0,1,male,39.0,0,0,0.0
818,Jonkheer. John George Reuchlin,0,1,male,38.0,0,0,0.0

## Adding Columns and Rows

In [64]:
# Adding a new column (with default or calculated values)
df['Status'] = 'Poor'

In [65]:
df.head()

,Name,Survived,Pclass,Sex,Age,SibSp,PaCh,Fare,Status
0,Mr. Owen Harris Braund,0,3,male,22.0,1,0,7.2500,Poor
1,Mrs. John Bradley (Florence Briggs Thayer) Cum...,1,1,female,38.0,1,0,71.2833,Poor
2,Miss. Laina Heikkinen,1,3,female,26.0,0,0,7.9250,Poor
3,Mrs. Jacques Heath (Lily May Peel) Futrelle,1,1,female,35.0,1,0,53.1000,Poor
4,Mr. William Henry Allen,0,3,male,35.0,0,0,8.0500,Poor

In [66]:
# fill the column based of certain condition
df.loc[df['Fare'] > 10, 'Status'] = 'Rich'

In [67]:
df.head()

,Name,Survived,Pclass,Sex,Age,SibSp,PaCh,Fare,Status
0,Mr. Owen Harris Braund,0,3,male,22.0,1,0,7.2500,Poor
1,Mrs. John Bradley (Florence Briggs Thayer) Cum...,1,1,female,38.0,1,0,71.2833,Rich
2,Miss. Laina Heikkinen,1,3,female,26.0,0,0,7.9250,Poor
3,Mrs. Jacques Heath (Lily May Peel) Futrelle,1,1,female,35.0,1,0,53.1000,Rich
4,Mr. William Henry Allen,0,3,male,35.0,0,0,8.0500,Poor

In [5]:
# You can also use np.where to get the same result
import numpy as np
df['Status'] = np.where(df['Fare'] < 10, 'Poor', np.where(df['Fare'] < 50, 'Avg_rich', 'Rich'))

In [6]:
df

,Survived,Pclass,Name,Sex,Age,SibSp,PaCh,Fare,Status
0,0,3,Mr. Owen Harris Braund,male,22.0,1,0,7.2500,Poor
1,1,1,Mrs. John Bradley (Florence Briggs Thayer) Cum...,female,38.0,1,0,71.2833,Rich
2,1,3,Miss. Laina Heikkinen,female,26.0,0,0,7.9250,Poor
3,1,1,Mrs. Jacques Heath (Lily May Peel) Futrelle,female,35.0,1,0,53.1000,Rich
4,0,3,Mr. William Henry Allen,male,35.0,0,0,8.0500,Poor
...,...,...,...,...,...,...,...,...,...
882,0,2,Rev. Juozas Montvila,male,27.0,0,0,13.0000,Avg_rich
883,1,1,Miss. Margaret Edith Graham,female,19.0,0,0,30.0000,Avg_rich
884,0,3,Miss. Catherine Helen Johnston,female,7.0,1,2,23.4500,Avg_rich
885,1,1,Mr. Karl Howell Behr,male,26.0,0,0,30.0000,Avg_rich
886,0,3,Mr. Patrick Dooley,male,32.0,0,0,7.7500,Poor

In [7]:
# Inserting at a specific position
# Insert at column position 1
df.insert(1, 'ID', 101)

In [8]:
df.head()

,Survived,ID,Pclass,Name,Sex,Age,SibSp,PaCh,Fare,Status
0,0,101,3,Mr. Owen Harris Braund,male,22.0,1,0,7.2500,Poor
1,1,101,1,Mrs. John Bradley (Florence Briggs Thayer) Cum...,female,38.0,1,0,71.2833,Rich
2,1,101,3,Miss. Laina Heikkinen,female,26.0,0,0,7.9250,Poor
3,1,101,1,Mrs. Jacques Heath (Lily May Peel) Futrelle,female,35.0,1,0,53.1000,Rich
4,0,101,3,Mr. William Henry Allen,male,35.0,0,0,8.0500,Poor

## Adding a row using loc (if index doesnt exist)

In [9]:
# Add a new row at index 2
df.loc[2] = [1, 101, 1, 'Tomi Jesu', 'female', 22, 1, 0, 15.0, 'Rich']

In [10]:
df.head()

,Survived,ID,Pclass,Name,Sex,Age,SibSp,PaCh,Fare,Status
0,0,101,3,Mr. Owen Harris Braund,male,22.0,1,0,7.2500,Poor
1,1,101,1,Mrs. John Bradley (Florence Briggs Thayer) Cum...,female,38.0,1,0,71.2833,Rich
2,1,101,1,Tomi Jesu,female,22.0,1,0,15.0000,Rich
3,1,101,1,Mrs. Jacques Heath (Lily May Peel) Futrelle,female,35.0,1,0,53.1000,Rich
4,0,101,3,Mr. William Henry Allen,male,35.0,0,0,8.0500,Poor

In [11]:
# to add at the buttom you can also use concat (use pd.concat),
# before now, you could use append()
new_row = pd.DataFrame([[1, 101, 2, 'Funmi Ajagun.', 'female', 25, 1, 0, 15.0, 'Rich']], columns=df.columns)

In [12]:
new_row

   Survived   ID  Pclass           Name     Sex  Age  SibSp  PaCh  Fare Status
0         1  101       2  Funmi Ajagun.  female   25      1     0  15.0   Rich

In [13]:
df = pd.concat([df, new_row], ignore_index=True)

In [14]:
df.tail()

,Survived,ID,Pclass,Name,Sex,Age,SibSp,PaCh,Fare,Status
883,1,101,1,Miss. Margaret Edith Graham,female,19.0,0,0,30.00,Avg_rich
884,0,101,3,Miss. Catherine Helen Johnston,female,7.0,1,2,23.45,Avg_rich
885,1,101,1,Mr. Karl Howell Behr,male,26.0,0,0,30.00,Avg_rich
886,0,101,3,Mr. Patrick Dooley,male,32.0,0,0,7.75,Poor
887,1,101,2,Funmi Ajagun.,female,25.0,1,0,15.00,Rich

## Dropping columns and rows

In [17]:
df.drop(columns=['ID'], inplace=True)
df.head()

,Survived,Pclass,Name,Sex,Age,SibSp,PaCh,Fare,Status
0,0,3,Mr. Owen Harris Braund,male,22.0,1,0,7.2500,Poor
1,1,1,Mrs. John Bradley (Florence Briggs Thayer) Cum...,female,38.0,1,0,71.2833,Rich
2,1,1,Tomi Jesu,female,22.0,1,0,15.0000,Rich
3,1,1,Mrs. Jacques Heath (Lily May Peel) Futrelle,female,35.0,1,0,53.1000,Rich
4,0,3,Mr. William Henry Allen,male,35.0,0,0,8.0500,Poor

In [18]:
# Dropping using axis argument
# Drop column

df.drop('Status', axis = 1, inplace=True)

In [19]:
df.head()

,Survived,Pclass,Name,Sex,Age,SibSp,PaCh,Fare
0,0,3,Mr. Owen Harris Braund,male,22.0,1,0,7.2500
1,1,1,Mrs. John Bradley (Florence Briggs Thayer) Cum...,female,38.0,1,0,71.2833
2,1,1,Tomi Jesu,female,22.0,1,0,15.0000
3,1,1,Mrs. Jacques Heath (Lily May Peel) Futrelle,female,35.0,1,0,53.1000
4,0,3,Mr. William Henry Allen,male,35.0,0,0,8.0500

In [20]:
# Drop row
df.drop(1, axis=0, inplace=True)
df.head()

,Survived,Pclass,Name,Sex,Age,SibSp,PaCh,Fare
0,0,3,Mr. Owen Harris Braund,male,22.0,1,0,7.2500
2,1,1,Tomi Jesu,female,22.0,1,0,15.0000
3,1,1,Mrs. Jacques Heath (Lily May Peel) Futrelle,female,35.0,1,0,53.1000
4,0,3,Mr. William Henry Allen,male,35.0,0,0,8.0500
5,0,3,Mr. James Moran,male,27.0,0,0,8.4583

## How to save you dataframe

In [23]:
# take note to always drop the default pandas index (this is always added by default
# secondly, you can also save to other file formats
df.to_csv(r'C:\Users\USER\OneDrive\Desktop\Webfala\pandas\new_titanic.csv', index=False)

In [25]:
new_df = pd.read_csv(r'C:\Users\USER\OneDrive\Desktop\Webfala\pandas\new_titanic.csv')
new_df

,Survived,Pclass,Name,Sex,Age,SibSp,PaCh,Fare
0,0,3,Mr. Owen Harris Braund,male,22.0,1,0,7.2500
1,1,1,Tomi Jesu,female,22.0,1,0,15.0000
2,1,1,Mrs. Jacques Heath (Lily May Peel) Futrelle,female,35.0,1,0,53.1000
3,0,3,Mr. William Henry Allen,male,35.0,0,0,8.0500
4,0,3,Mr. James Moran,male,27.0,0,0,8.4583
...,...,...,...,...,...,...,...,...
882,1,1,Miss. Margaret Edith Graham,female,19.0,0,0,30.0000
883,0,3,Miss. Catherine Helen Johnston,female,7.0,1,2,23.4500
884,1,1,Mr. Karl Howell Behr,male,26.0,0,0,30.0000
885,0,3,Mr. Patrick Dooley,male,32.0,0,0,7.7500
886,1,2,Funmi Ajagun.,female,25.0,1,0,15.0000

## Pandas Data Inspection & Cleaning

In [1]:
import pandas as pd

In [2]:
df = pd.read_csv(r'C:\Users\USER\OneDrive\Desktop\Webfala\pandas\dirty_data.csv')
df.head()

   Duration          Date  Pulse  Maxpulse  Calories
0        60  '2020/12/01'    110       130     409.1
1        60  '2020/12/02'    117       145     479.0
2        60  '2020/12/03'    103       135     340.0
3        45  '2020/12/04'    109       175     282.4
4        45  '2020/12/05'    117       148     406.0

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 32 entries, 0 to 31
Data columns (total 5 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Duration  32 non-null     int64
 1   Date      31 non-null     object
 2   Pulse     32 non-null     int64
 3   Maxpulse  32 non-null     int64
 4   Calories  30 non-null     float64
dtypes: float64(1), int64(3), object(1)
memory usage: 1.4+ KB

In [ ]:
# Handling Missing Data

# first, we need to identify missing values
# This function:
# Returns a new table of the exact same size as the original (don't do this for large data set
# Fills every spot with True if the value is missing (like NaN or None).
# Fills the spot with False if the value is present and valid
# Boolean DataFrame

df.isna() # or df.isnull()

In [5]:
df.loc[df.isna().any(axis=1), df.isna().any(axis=0)]

            Date  Calories
18  '2020/12/18'       NaN
22           NaN     282.0
28  '2020/12/28'       NaN

In [7]:
### OR 
df.loc[df.isna().any(axis=1)]

    Duration          Date  Pulse  Maxpulse  Calories
18        45  '2020/12/18'     90       112       NaN
22        45           NaN    100       119     282.0
28        60  '2020/12/28'    103       132       NaN

In [8]:
# To just return the count of Nans per column
df.isna().sum()

Duration    0
Date        1
Pulse       0
Maxpulse    0
Calories    2
dtype: int64

## How to handle missing data

## <b> 1. Dropping Missing Data (dropna): If the missing data is minimal (e.g., less than 5% of your dataset), you can remove it using df.dropna()

In [4]:
# Drop missing values
# Drop rows with any NaNs
# Take note of the axis=0, how='any arguments
df.dropna(inplace=True)

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 29 entries, 0 to 31
Data columns (total 5 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Duration  29 non-null     int64
 1   Date      29 non-null     object
 2   Pulse     29 non-null     int64
 3   Maxpulse  29 non-null     int64
 4   Calories  29 non-null     float64
dtypes: float64(1), int64(3), object(1)
memory usage: 1.4+ KB

In [6]:
df = pd.read_csv(r'C:\Users\USER\OneDrive\Desktop\Webfala\pandas\dirty_data.csv')

In [7]:
# Drop rows where all values are NaN
df.dropna(how='all', inplace=True)
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 32 entries, 0 to 31
Data columns (total 5 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Duration  32 non-null     int64
 1   Date      31 non-null     object
 2   Pulse     32 non-null     int64
 3   Maxpulse  32 non-null     int64
 4   Calories  30 non-null     float64
dtypes: float64(1), int64(3), object(1)
memory usage: 1.4+ KB

In [8]:
# you can choose to drop from a particular row by using subset (just use a list containing the column names)
# Drop rows where 'Date' is NaN
df.dropna(subset=['Date'], inplace=True)
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 31 entries, 0 to 31
Data columns (total 5 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Duration  31 non-null     int64
 1   Date      31 non-null     object
 2   Pulse     31 non-null     int64
 3   Maxpulse  31 non-null     int64
 4   Calories  29 non-null     float64
dtypes: float64(1), int64(3), object(1)
memory usage: 1.5+ KB

In [ ]:
# Lastly, you can drop entire column
# Remove any column containing missing data.python
# We hardly do this in practice
# df.dropna(axis=1)

In [ ]:
# We also have threshold (thresh):
# Keeps rows/columns only if they contain at least N non-null values.
# df.dropna(thresh=3)

## <b> Filling Missing Data (fillna): When you cannot afford to lose
## data, you can replace missing cells with alternative values using df.fillna() <b>

In [18]:
df = pd.read_csv(r'C:\Users\USER\OneDrive\Desktop\Webfala\pandas\dirty_data.csv')

In [10]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 32 entries, 0 to 31
Data columns (total 5 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Duration  32 non-null     int64
 1   Date      31 non-null     object
 2   Pulse     32 non-null     int64
 3   Maxpulse  32 non-null     int64
 4   Calories  30 non-null     float64
dtypes: float64(1), int64(3), object(1)
memory usage: 1.4+ KB

In [15]:
# Constant value substitution: Fills every missing cell with a specific n
# Fill all NaNs with 0
# But this might not be suitable in all cases
df.fillna(0, inplace=True) 
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 32 entries, 0 to 31
Data columns (total 5 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Duration  32 non-null     int64
 1   Date      32 non-null     object
 2   Pulse     32 non-null     int64
 3   Maxpulse  32 non-null     int64
 4   Calories  32 non-null     float64
dtypes: float64(1), int64(3), object(1)
memory usage: 1.4+ KB

In [14]:
# Fill with a default string (not really useful too) only for place where your values are strings

df['Calories'].fillna('Unknown')
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 32 entries, 0 to 31
Data columns (total 5 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Duration  32 non-null     int64
 1   Date      31 non-null     object
 2   Pulse     32 non-null     int64
 3   Maxpulse  32 non-null     int64
 4   Calories  30 non-null     float64
dtypes: float64(1), int64(3), object(1)
memory usage: 1.4+ KB

In [19]:
# Statistical Imputation (Numerical columns):
# Replaces missing data with the column's mean, median, or mode.

# df['Calories'].fillna(df['Calories'].mean(), inplace=True) # old way

df['Calories'] = df['Calories'].fillna(df['Calories'].mean())

In [20]:
df.isna().sum()

Duration    0
Date        1
Pulse       0
Maxpulse    0
Calories    0
dtype: int64

In [21]:
df.loc[df.isna().any(axis=1), df.isna().any(axis=0)]

   Date
22  NaN

# Checking and Removing Duplicates

In [22]:
df.duplicated().any()

np.True_

In [23]:
# Setting keep=False ensures all occurrences of the duplicate rows are marked as True so you can see them side_by_side.
#Use loc to return row or column

df.loc[df.duplicated(keep=False), :]

    Duration          Date  Pulse  Maxpulse  Calories
11        60  '2020/12/12'    100       120     250.7
12        60  '2020/12/12'    100       120     250.7

In [24]:
# Drop duplicates
# Keep first by default
df.drop_duplicates(inplace=True)

In [25]:
df.duplicated().any()

np.False_

In [ ]:
# Keep last occurrence

df.drop_duplicates(keep='last')
# I didn't actually run them on this

## Data Type Conversion
You can convert columns to different types using astype().

In [26]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 31 entries, 0 to 31
Data columns (total 5 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Duration  31 non-null     int64
 1   Date      30 non-null     object
 2   Pulse     31 non-null     int64
 3   Maxpulse  31 non-null     int64
 4   Calories  31 non-null     float64
dtypes: float64(1), int64(3), object(1)
memory usage: 1.5+ KB

In [27]:
# Our maxpulse is int, let's change it to float

df['Maxpulse'] = df['Maxpulse'].astype('float')
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 31 entries, 0 to 31
Data columns (total 5 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Duration  31 non-null     int64
 1   Date      30 non-null     object
 2   Pulse     31 non-null     int64
 3   Maxpulse  31 non-null     float64
 4   Calories  31 non-null     float64
dtypes: float64(2), int64(2), object(1)
memory usage: 1.5+ KB

## String Manipulation Using .str

In [28]:
df = pd.read_csv(r"C:\Users\USER\OneDrive\Desktop\Webfala\pandas\titanic.csv")
df.head()

,Survived,Pclass,Name,Sex,Age,SibSp,PaCh,Fare
0,0,3,Mr. Owen Harris Braund,male,22.0,1,0,7.2500
1,1,1,Mrs. John Bradley (Florence Briggs Thayer) Cum...,female,38.0,1,0,71.2833
2,1,3,Miss. Laina Heikkinen,female,26.0,0,0,7.9250
3,1,1,Mrs. Jacques Heath (Lily May Peel) Futrelle,female,35.0,1,0,53.1000
4,0,3,Mr. William Henry Allen,male,35.0,0,0,8.0500

In [29]:
df['Name'].str.lower()  # all lowercase

# If i wanted to return an updated df
# df["Name"] = df["Name"].str.lower()

0                                 mr. owen harris braund
1      mrs. john bradley (florence briggs thayer) cum...
2                                  miss. laina heikkinen
3            mrs. jacques heath (lily may peel) futrelle
4                                mr. william henry allen
                             ...
882                                 rev. juozas montvila
883                          miss. margaret edith graham
884                       miss. catherine helen johnston
885                                 mr. karl howell behr
886                                   mr. patrick dooley
Name: Name, Length: 887, dtype: object

In [30]:
df['Name'].str.upper()

0                                 MR. OWEN HARRIS BRAUND
1      MRS. JOHN BRADLEY (FLORENCE BRIGGS THAYER) CUM...
2                                  MISS. LAINA HEIKKINEN
3            MRS. JACQUES HEATH (LILY MAY PEEL) FUTRELLE
4                                MR. WILLIAM HENRY ALLEN
                             ...
882                                 REV. JUOZAS MONTVILA
883                          MISS. MARGARET EDITH GRAHAM
884                       MISS. CATHERINE HELEN JOHNSTON
885                                 MR. KARL HOWELL BEHR
886                                   MR. PATRICK DOOLEY
Name: Name, Length: 887, dtype: object

In [31]:
df['Name'].str.title()

0                                 Mr. Owen Harris Braund
1      Mrs. John Bradley (Florence Briggs Thayer) Cum...
2                                  Miss. Laina Heikkinen
3            Mrs. Jacques Heath (Lily May Peel) Futrelle
4                                Mr. William Henry Allen
                             ...
882                                 Rev. Juozas Montvila
883                          Miss. Margaret Edith Graham
884                       Miss. Catherine Helen Johnston
885                                 Mr. Karl Howell Behr
886                                   Mr. Patrick Dooley
Name: Name, Length: 887, dtype: object

In [32]:
df['Name'].str.strip()

0                                 Mr. Owen Harris Braund
1      Mrs. John Bradley (Florence Briggs Thayer) Cum...
2                                  Miss. Laina Heikkinen
3            Mrs. Jacques Heath (Lily May Peel) Futrelle
4                                Mr. William Henry Allen
                             ...
882                                 Rev. Juozas Montvila
883                          Miss. Margaret Edith Graham
884                       Miss. Catherine Helen Johnston
885                                 Mr. Karl Howell Behr
886                                   Mr. Patrick Dooley
Name: Name, Length: 887, dtype: object

In [33]:
df['Name'].str.replace(' ', '_') # replace space with underscore

0                                 Mr._Owen_Harris_Braund
1      Mrs._John_Bradley_(Florence_Briggs_Thayer)_Cum...
2                                  Miss._Laina_Heikkinen
3            Mrs._Jacques_Heath_(Lily_May_Peel)_Futrelle
4                                Mr._William_Henry_Allen
                             ...
882                                 Rev._Juozas_Montvila
883                          Miss._Margaret_Edith_Graham
884                       Miss._Catherine_Helen_Johnston
885                                 Mr._Karl_Howell_Behr
886                                   Mr._Patrick_Dooley
Name: Name, Length: 887, dtype: object

## Combining DataFrames

In [34]:
# a. concat(): Combine along rows or columns
data1 =  {
 'Name': ['Rhoda', 'Jemilah', 'Rahmat', 'Esther'],
 'Age': [25, 30, 35, 10],
 'City': ['Ilorin', 'Lagos', 'Ibadan', 'Abuja']
}

df1 = pd.DataFrame(data1)
df1

      Name  Age    City
0    Rhoda   25  Ilorin
1  Jemilah   30   Lagos
2   Rahmat   35  Ibadan
3   Esther   10   Abuja

In [35]:
data2 = {
 'Name': ['Abiola', 'Nofisat', 'Salamat', 'Lola'],
 'Age': [20, 20, 35, 11],
 'City': ['Abuja', 'Akure', 'Mina', 'Kano']
}

df2 = pd.DataFrame(data2)
df2

      Name  Age   City
0   Abiola   20  Abuja
1  Nofisat   20  Akure
2  Salamat   35   Mina
3     Lola   11   Kano

In [38]:
# Stack rows
# remember the concat we did earlier?
# remeber to ignore index

pd.concat([df1, df2], axis=0, ignore_index=True)

      Name  Age    City
0    Rhoda   25  Ilorin
1  Jemilah   30   Lagos
2   Rahmat   35  Ibadan
3   Esther   10   Abuja
4   Abiola   20   Abuja
5  Nofisat   20   Akure
6  Salamat   35    Mina
7     Lola   11    Kano

In [39]:
# Side-by-side
# we don't need to ignore index here

pd.concat([df1, df2], axis=1)

      Name  Age    City     Name  Age   City
0    Rhoda   25  Ilorin   Abiola   20  Abuja
1  Jemilah   30   Lagos  Nofisat   20  Akure
2   Rahmat   35  Ibadan  Salamat   35   Mina
3   Esther   10   Abuja     Lola   11   Kano

In [ ]:
# merge(): SQL-style joins on columns
# Inner join by default

pd.merge(df1, df2, on='Age')

# combines df1 and df2 side-by-side by matching rows that share the same
# Includes only matching keys from both DataFrames. Rows with keys that d